// <auto-generated />
using System;
using ExpenseTracker.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 230m,
                            Category = "Electronics",
                            Date = new DateTime(2026, 5, 8, 20, 50, 8, 159, DateTimeKind.Local).AddTicks(4924),
                            Description = "Motherboard"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 410m,
                            Category = "Electronics",
                            Date = new DateTime(2026, 5, 8, 20, 50, 8, 159, DateTimeKind.Local).AddTicks(4936),
                            Description = "CPU"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 40m,
                            Category = "Peripherals",
                            Date = new DateTime(2026, 5, 8, 20, 50, 8, 159, DateTimeKind.Local).AddTicks(4937),
                            Description = "Keyboard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
